apiVersion: apps/v1
kind: Deployment
metadata:
  name: Shop
  labels:
    app: Shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Shop
  template:
    metadata:
      labels:
        app: Shop
    spec:
      containers:
        - name: Shop
          image: username/Shop:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
