server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /orderInfos/**
        - id: Shop
          uri: http://localhost:8082
          predicates:
            - Path=/orderManages/**, /orderDtls/**
        - id: Pay
          uri: http://localhost:8083
          predicates:
            - Path=/pays/**, 
        - id: CustHelp
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: Delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, /cmpltTrts/**, /deliveryInfos/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /orderInfos/**
        - id: Shop
          uri: http://shop:8080
          predicates:
            - Path=/orderManages/**, /orderDtls/**
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/**, 
        - id: CustHelp
          uri: http://custHelp:8080
          predicates:
            - Path=, 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, /cmpltTrts/**, /deliveryInfos/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
