---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    selector: 
      matchLabels: 
        app: "order"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "order"
      spec: 
        containers: 
          - 
            name: "order"
            image: "order"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "order"
    labels: 
      app: "order"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "order"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "shop"
    labels: 
      app: "shop"
  spec: 
    selector: 
      matchLabels: 
        app: "shop"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "shop"
      spec: 
        containers: 
          - 
            name: "shop"
            image: "shop"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "shop"
    labels: 
      app: "shop"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "shop"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "pay"
    labels: 
      app: "pay"
  spec: 
    selector: 
      matchLabels: 
        app: "pay"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "pay"
      spec: 
        containers: 
          - 
            name: "pay"
            image: "pay"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "pay"
    labels: 
      app: "pay"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "pay"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "custhelp"
    labels: 
      app: "custhelp"
  spec: 
    selector: 
      matchLabels: 
        app: "custhelp"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "custhelp"
      spec: 
        containers: 
          - 
            name: "custhelp"
            image: "custhelp"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "custhelp"
    labels: 
      app: "custhelp"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "custhelp"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    selector: 
      matchLabels: 
        app: "delivery"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "delivery"
      spec: 
        containers: 
          - 
            name: "delivery"
            image: "delivery"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "delivery"
    labels: 
      app: "delivery"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "delivery"
